export const ICPC2 = [
    'Medisinsk undersøkelse/helsevurdering generell/fullstendig',
    'Medisinsk undersøkelse/helsevurdering målrettet/partiell',
    'Sensitivitetsprøve',
    'Mikrobiologisk/immunologisk prøve',
    'Blodprøve IKA',
    'Urinprøve IKA',
    'Avføringsprøve IKA',
    'Histologisk/cytologisk prøve',
    'Laboratorieprøve IKA',
    'Fysisk funksjonsprøve',
    'Endoskopi',
    'Røntgen/annen billeddiagnostikk',
    'Biosignalundersøkelse IKA',
    'Diagnostisk prosedyre IKA',
    'Forebyggende vaksinering/medisinering',
    'Observasjon/helseopplysning/rådgivning',
    'Kontakt med helsepersonell i primærhelsetjenesten',
    'Kontakt med spesialist',
    'Avklaring/diskusjon av pasientens behov/kontaktårsak',
    'Forebyggende prosedyre IKA',
    'Legemiddelforskrivning/-administrasjon',
    'Incisjon/tapping/aspirasjon',
    'Eksisjon/fjerning av vev/biopsi/skraping/kauterisasjon',
    'Instrumentering/kateterisering/intubasjon/dilatasjon',
    'Reparasjon/fiksasjon med sutur/gips/protese påføring og fjerning',
    'Lokal injeksjon/infiltrasjon',
    'Bandasjering/kompresjon/tamponade',
    'Fysikalsk behandling/rehabilitering',
    'Terapeutisk rådgivning/samtale',
    'Andre terapeutiske prosedyrer/småkirurgi IKA',
    'Resultat av prøve/prosedyre',
    'Resultat av undersøkelse/prøve ved journal/brev fra annen helsetjenesteyter',
    'Administrativ prosedyre',
    'Observasjon/oppfølgingskontakt IKA',
    'Kontakt/helseproblem initiert/formidlet av helsepersonell',
    'Kontakt/helseproblem initiert/formidlet av annen enn pasient/helsepersonell',
    'Henvisning til annen primærhelsetjeneste/tjenesteyter',
    'Henvisning til spesialist/sykehus',
    'Henvisning IKA',
    'Kontaktårsak IKA',
    'Smerte generell/flere steder',
    'Frysninger',
    'Feber',
    'Slapphet/tretthet',
    'Sykdomsfølelse',
    'Besvimelse/synkope',
    'Bevisstløshet/koma',
    'Hevelse/oppfylning IKA',
    'Svetteproblemer',
    'Blødning IKA',
    'Brystsmerte IKA',
    'Engstelig for behandling',
    'Irritabelt/urolig spedbarn',
    'Bekymret/opptatt av utseende IKA',
    'Dødshjelp diskusjon/spørsmål om',
    'Økt risiko for ondartet svulst',
    'Risiko for sykdom IKA',
    'Engstelig for døden',
    'Engstelig for kreft IKA',
    'Engstelig for sykdom IKA',
    'Redusert funksjonsevne IKA',
    'Generelle symptomer/plager IKA',
    'Tuberkulose',
    'Meslinger',
    'Vannkopper',
    'Malaria',
    'Røde hunder',
    'Mononukleose',
    'Virussykdom med utslett IKA',
    'Virussykdom IKA',
    'Infeksjonssykdom IKA',
    'Ondartet svulst IKA',
    'Skade/traume IKA',
    'Multiple skader/traumer',
    'Følgetilstand etter skade/traume',
    'Legemiddelforgiftning',
    'Bivirkning av legemiddel',
    'Toksisk virkning av ikke-medisinsk stoff',
    'Komplikasjon etter medisinsk behandling',
    'Skadevirkning av fysisk faktor',
    'Komplikasjoner/problemer med protese',
    'Medfødt feil IKA/multiple medfødte feil',
    'Unormalt resultat ved undersøkelse IKA',
    'Allergi/allergisk reaksjon IKA',
    'Prematurt/immaturt født barn',
    'Perinatal sykelighet IKA',
    'Perinatal død',
    'Død/dødsfall IKA',
    'Kontakt/undersøkelse for administrativt formål',
    'Individforebyggende tiltak',
    'Cytologi livmorhals screening',
    'Helseproblem/sykdom ikke spesifisert/lokalisert',
    'Lymfeknuter forstørrede/smertefulle',
    'Blod/blodsystemet symptomer/plager',
    'Engstelig for HIV/AIDS',
    'Engstelig for kreft i blod- og lymfesystemet',
    'Engstelig for sykdom i blod- og lymfesystemet IKA',
    'Redusert funksjonsevne pga blod/lymfe-problem',
    'Blod/lymfesystem symptomer/plager IKA',
    'Lymfadenitt akutt',
    'Lymfadenitt kronisk/uspesifikk',
    'Hodgkins sykdom/lymfom',
    'Leukemi',
    'Ondartet svulst i blod/lymfesystemet IKA',
    'Godartet/uspesifisert svulst i blod/lymfesystemet',
    'Miltruptur traumatisk',
    'Skade i blod/lymfesystemet IKA',
    'Arvelig hemolytisk anemi',
    'Medfødt feil i blod/lymfesystemet IKA',
    'Jernmangelanemi',
    'Anemi ved vitamin B12-/folsyremangel',
    'Anemi IKA',
    'Purpura/koagulasjonsdefekt',
    'Unormale hvite blodceller',
    'Forstørret milt',
    'HIV-sykdom/AIDS',
    'Blod/lymfe/milt sykdom IKA',
    'Abdominalsmerte/krampe generell',
    'Abdominalsmerte epigastriet',
    'Halsbrann',
    'Endetarmssmerte',
    'Perianal kløe',
    'Abdominalsmerte lokalisert IKA',
    'Dyspepsi/fordøyelsesbesvær',
    'Flatulens/oppblåsthet/raping',
    'Kvalme',
    'Oppkast/brekninger',
    'Diaré',
    'Forstoppelse',
    'Gulsott',
    'Oppkast med blod/hematemese',
    'Melena',
    'Rektalblødning',
    'Inkontinens avføring',
    'Endring i avføring/avføringsvane',
    'Tenner/tannkjøtt symptomer/plager',
    'Munn/tunge/leppe symptomer/plager',
    'Svelgebesvær',
    'Forstørret lever',
    'Abdominal oppfylling/kul IKA',
    'Utspilt abdomen',
    'Engstelig for kreft i fordøyelsessystemet',
    'Engstelig for sykdom i fordøyelsessystemet IKA',
    'Redusert funksjonsevne pga fordøyelsesproblem',
    'Fordøyelsessystemet symptomer/plager IKA',
    'Tarminfeksjon',
    'Kusma',
    'Virushepatitt',
    'Gastroenteritt antatt infeksiøs',
    'Ondartet svulst i magesekk',
    'Ondartet svulst i tykktarm/endetarm',
    'Ondartet svulst i bukspyttkjertel',
    'Ondartet svulst i fordøyelsessystemet IKA',
    'Godartet/uspesifisert svulst i fordøyelsesystemet',
    'Fremmedlegeme i fordøyelsesystemet',
    'Skade i fordøyelsessystemet IKA',
    'Medfødt feil i fordøyelsessystemet',
    'Tenner/tannkjøtt sykdom',
    'Munn/tunge/lepper sykdom',
    'Spiserørssykdom',
    'Sår i tolvfingertarm',
    'Magesår IKA',
    'Funksjonelle plager i magesekk',
    'Appendisitt',
    'Lyskebrokk',
    'Mellomgulvsbrokk',
    'Abdominalt brokk IKA',
    'Divertikkelsykdom i tarm',
    'Irritabel tarm-syndrom',
    'Kronisk enteritt/ulcerøs kolitt',
    'Analfissur/perianal abscess',
    'Orme-/parasittsykdom',
    'Leversykdom IKA',
    'Galleveisbetennelse/gallesten',
    'Sykdom i fordøyelsessystemet IKA',
    'Øyesmerte',
    'Rødt øye',
    'Tåreflod/sekresjon øye',
    'Synlige flekker/tråder i synsfeltet',
    'Synsforstyrrelse IKA',
    'Øye unormal følelse',
    'Øye unormal bevegelse',
    'Øye unormalt utseende',
    'Øyelokk symptomer/plager',
    'Briller symptomer/plager',
    'Kontaktlinser symptomer/plager',
    'Engstelig for øyesykdom',
    'Redusert funksjonsevne pga øyeproblem',
    'Øye symptomer/plager IKA',
    'Infeksiøs konjunktivitt',
    'Allergisk konjunktivitt',
    'Øyelokkbetennelse',
    'Øye infeksjon/betennelse IKA',
    'Svulst i øye/øyehule',
    'Kontusjon/blødning i øye',
    'Fremmedlegeme i øye',
    'Skade i øye IKA',
    'Tåreveisstenose/atresi hos spedbarn',
    'Medfødt feil i øye IKA',
    'Netthinneløsning/rift',
    'Retinopati',
    'Makuladegenerasjon',
    'Hornhinnesår',
    'Trakom',
    'Brytningsforstyrrelse',
    'Grå stær/katarakt',
    'Glaukom',
    'Blindhet',
    'Skjeling/strabisme',
    'Øyesykdom IKA',
    'Øresmerte/øreverk',
    'Hørsel symptomer/plager',
    'Øresus',
    'Øreflod/sekresjon',
    'Blødning øre',
    'Øreplugg/øretetthet',
    'Bekymret/opptatt av ørenes utseende',
    'Engstelig for hørselsproblemer/øresykdom',
    'Redusert funksjonsevne pga øreproblem',
    'Øre symptomer/plager IKA',
    'Ytre øre betennelse',
    'Mellomørebetennelse akutt',
    'Mellomørebetennelse serøs',
    'Tuba auditiva betennelse',
    'Mellomørebetennelse kronisk',
    'Svulst i øre',
    'Fremmedlegeme i øre',
    'Perforert trommehinne IKA',
    'Overflateskade på ytre øre',
    'Skade øre IKA',
    'Medfødt feil i øre',
    'Ørevoks',
    'Svimmelhetssyndrom',
    'Otosklerose',
    'Hørselstap aldersbetinget',
    'Hørselstap pga støyskade',
    'Døvhet/hørselstap IKA',
    'Øresykdom IKA',
    'Smerte relatert til hjertet',
    'Trykk/sammensnøring hjertet',
    'Smerte relatert til kretsløpet IKA',
    'Hjertebank',
    'Uregelmessige hjerteslag IKA',
    'Utvidede vener',
    'Hovne ankler/ødem',
    'Økt risiko for hjerte-karsykdom',
    'Engstelig for hjertesykdom',
    'Engstelig for høyt blodtrykk',
    'Engstelig for hjerte-karsykdom IKA',
    'Redusert funksjonsevne pga hjerte-karproblem',
    'Hjerte-karsystemet symptomer/plager IKA',
    'Infeksjon i hjerte-karsystemet',
    'Reumatisk feber/hjertesykdom',
    'Svulst i hjerte',
    'Medfødt feil i hjerte-karsystemet',
    'Iskemisk hjertesykdom med angina pectoris',
    'Akutt hjerteinfarkt',
    'Iskemisk hjertesykdom kronisk IKA',
    'Hjertesvikt',
    'Atrieflimmer/flutter',
    'Paroksysmal takykardi',
    'Hjertearytmi IKA',
    'Bilyd hjerte/arterier IKA',
    'Pulmonal hjertesykdom',
    'Hjerteklaffesykdom IKA',
    'Hjertesykdom IKA',
    'Forhøyet blodtrykk IKA',
    'Hypertensjon ukomplisert',
    'Hypertensjon med organkomplikasjoner',
    'Postural hypotensjon',
    'Anfall med forbigående cerebral iskemi',
    'Hjerneslag',
    'Cerebrovaskulær sykdom',
    'Aterosklerose/perifer karsykdom',
    'Lungeemboli',
    'Årebetennelse',
    'Åreknuter på underekstremitet',
    'Hemoroider',
    'Hjerte-karsykdom IKA',
    'Nakke symptomer/plager',
    'Rygg symptomer/plager',
    'Korsrygg symptomer/plager',
    'Brystkasse symptomer/plager',
    'Flanke/armhule symptomer/plager',
    'Kjeve symptomer/plager',
    'Skulder symptomer/plager',
    'Arm symptomer/plager',
    'Albue symptomer/plager',
    'Håndledd symptomer/plager',
    'Hånd/finger symptomer/plager',
    'Hofte symptomer/plager',
    'Legg/lår symptomer/plager',
    'Kne symptomer/plager',
    'Ankel symptomer/plager',
    'Fot/tå symptomer/plager',
    'Utbredte muskelsmerter/fibromyalgi',
    'Muskel symptomer/plager IKA',
    'Ledd symptomer/plager IKA',
    'Engstelig for kreft i muskel- og skjelettsystemet',
    'Engstelig for sykdom i muskel- og skjelettsystemet IKA',
    'Redusert funksjonsevne pga muskel-skjelettproblem',
    'Muskel- og skjelettsystemet symptomer/plager IKA',
    'Infeksjon i muskel- og skjelettsystemet',
    'Ondartet svulst i muskel- og skjelettsystemet',
    'Brudd underarm',
    'Brudd legg/ankel',
    'Brudd hånd/fot',
    'Brudd lårben/lårhals',
    'Brudd IKA',
    'Forstuving/forstrekking ankel',
    'Forstuving/forstrekking kne',
    'Forstuving/forstrekking ledd IKA',
    'Dislokasjon/subluksasjon',
    'Skade i muskel- og skjelettsystemet IKA',
    'Medfødt feil i muskel- og skjelettsystemet',
    'Nakkesyndrom',
    'Ryggsyndrom uten smerteutstråling',
    'Ervervet deformitet av ryggsøylen',
    'Ryggsyndrom med smerteutstråling',
    'Bursitt/tendinitt/synovitt IKA',
    'Reumatoid artritt/reumatisk sykdom',
    'Hofteleddsartrose',
    'Kneleddsartrose',
    'Artrose IKA',
    'Skuldersyndrom',
    'Tennisalbue/lateral epikondylitt',
    'Osteokondrose',
    'Osteoporose',
    'Akutt indre kneskade',
    'Godartet/uspesifisert svulst i muskel- og skjelettsystemet',
    'Ervervet deformitet av ekstremitet',
    'Muskel- og skjelettsykdom IKA',
    'Hodepine',
    'Ansiktssmerte',
    'Restless legs',
    'Prikking/parestesi i hender/føtter',
    'Forstyrrelser i hudens følsomhet IKA',
    'Krampeanfall/kramper',
    'Unormale/ufrivillige bevegelser',
    'Forstyrrelse i lukt/smak',
    'Svimmelhet IKA',
    'Lammelse/svakhet',
    'Talevansker',
    'Engstelig for kreft i nervesystemet',
    'Engstelig for sykdom i nervesystemet IKA',
    'Redusert funksjonsevne pga problem i nervesystemet',
    'Nervesystemet symptomer/plager IKA',
    'Poliomyelitt',
    'Meningitt/encefalitt',
    'Stivkrampe',
    'Infeksjon i sentralnervesystemet IKA',
    'Ondartet svulst i nervesystemet',
    'Godartet svulst i nervesystemet',
    'Uspesifisert svulst i nervesystemet',
    'Hjernerystelse',
    'Hodeskade IKA',
    'Skade i nervesystemet IKA',
    'Medfødt feil i nervesystemet',
    'Multippel sklerose',
    'Parkinsonisme',
    'Epilepsi',
    'Migrene',
    'Cluster-hodepine',
    'Facialisparese',
    'Trigeminusnevralgi',
    'Carpal tunnel syndrom',
    'Perifer nevropati',
    'Tensjonshodepine',
    'Sykdom i nervesystemet IKA',
    'Følelse av angst/nervøsitet/anspenthet',
    'Psykisk ubalanse situasjonsbetinget',
    'Depresjonsfølelse',
    'Irritabel atferd/følelse',
    'Søvnforstyrrelse',
    'Seksuell drift/lyst hemmet',
    'Seksuell tilfredsstillelse hemmet',
    'Seksuell legning bekymring for',
    'Stamming/tics',
    'Spiseforstyrrelse hos barn',
    'Sengevæting/enuresis IKA',
    'Enkoprese',
    'Kronisk alkoholmisbruk',
    'Akutt alkoholmisbruk',
    'Tobakkmisbruk',
    'Legemiddelmisbruk',
    'Stoffmisbruk',
    'Hukommelsesforstyrrelse',
    'Atferdsforstyrrelse hos barn',
    'Atferdsforstyrrelse hos ungdom',
    'Spesifikke utviklingsforstyrrelser',
    'Livsfaseproblem hos voksen',
    'Engstelig for psykisk sykdom',
    'Redusert funksjonsevne pga psykisk problem',
    'Psykiske symptomer/plager IKA',
    'Demens',
    'Organisk psykisk lidelse IKA',
    'Schizofreni',
    'Affektiv lidelse',
    'Angstlidelse',
    'Dissosiativ/somatoform lidelse',
    'Depressiv lidelse',
    'Selvmord/selvmordsforsøk',
    'Nevrasteni',
    'Fobi/obsessiv-kompulsiv lidelse',
    'Personlighetsforstyrrelse',
    'Hyperkinetisk forstyrrelse',
    'Posttraumatisk stresslidelse',
    'Psykisk utviklingshemning',
    'Anorexia nervosa/bulimi',
    'Psykose IKA',
    'Psykisk lidelse IKA',
    'Smerte i luftveier',
    'Kortpustethet/dyspné',
    'Piping i brystet',
    'Pusteproblem IKA',
    'Hoste',
    'Neseblødning',
    'Nysing/tetthet i nese',
    'Nese symptomer/plager IKA',
    'Bihule symptomer/plager IKA',
    'Hals symptomer/plager',
    'Stemme symptomer/plager',
    'Blodig oppspytt/hemoptyse',
    'Unormalt oppspytt/ekspektorat',
    'Engstelig for kreft i luftveiene',
    'Engstelig for sykdom i luftveiene IKA',
    'Redusert funksjonsevne pga luftveisproblem',
    'Luftveiene symptomer/plager IKA',
    'Kikhoste',
    'Streptokokkhals',
    'Nesebyll',
    'Akutt øvre luftveisinfeksjon',
    'Bihulebetennelse',
    'Akutt tonsillitt',
    'Akutt laryngitt/trakeitt',
    'Akutt bronkitt/bronkiolitt',
    'Kronisk bronkitt',
    'Influensa',
    'Lungebetennelse',
    'Pleuritt IKA',
    'Luftveisinfeksjon IKA',
    'Ondartet svulst i bronkie/lunge',
    'Ondartet svulst i luftveiene IKA',
    'Godartet svulst i luftveiene',
    'Fremmedlegeme i nese/larynks/bronkie',
    'Skade i luftveiene IKA',
    'Medfødt feil i luftveiene',
    'Hypertrofi av tonsiller/adenoid vev',
    'Uspesifisert svulst i luftveiene',
    'Kronisk obstruktiv lungesykdom',
    'Astma',
    'Allergisk rinitt',
    'Hyperventileringssyndrom',
    'Luftveissykdom IKA',
    'Smerte/ømhet i huden',
    'Hudkløe',
    'Vorter',
    'Lokalisert hevelse/kul i huden',
    'Utbredte hevelser/kuler i huden',
    'Lokalisert utslett i huden',
    'Utbredt utslett i huden',
    'Forandring av hudfargen IKA',
    'Infeksjon i finger/tå',
    'Abscess/furunkel',
    'Hudinfeksjon posttraumatisk',
    'Insektstikk/bitt',
    'Bitt av dyr/menneske',
    'Forbrenning/skålding',
    'Fremmedlegeme i huden',
    'Kontusjon/slag hud',
    'Skrubbsår/blemmer',
    'Åpent sår/kutt',
    'Skade i hud/underhud IKA',
    'Liktorn/fortykket underhud',
    'Hudstruktur symptomer/plager',
    'Negl symptomer/plager',
    'Håravfall/skallethet',
    'Hår/hodebunn symptomer/plager IKA',
    'Engstelig for kreft i huden',
    'Engstelig for hudsykdom IKA',
    'Redusert funksjonsevne pga hudproblem',
    'Hud symptomer/plager IKA',
    'Herpes zoster',
    'Herpes simplex IKA',
    'Infestasjon av midd',
    'Infestasjon av parasitt IKA',
    'Ringorm/hudsopp IKA',
    'Candidainfeksjon i huden',
    'Hudinfeksjon IKA',
    'Ondartet svulst i huden',
    'Lipom',
    'Godartet/uspesifisert svulst i huden IKA',
    'Solutløst keratose/solforbrenning',
    'Hemangiom/lymfangiom',
    'Pigmentnevus',
    'Medfødt feil i hud/underhud IKA',
    'Brennkopper',
    'Pilonidalcyste/-fistel',
    'Seboréisk dermatitt',
    'Atopisk dermatitt/eksem',
    'Kontaktdermatitt/allergisk dermatitt IKA',
    'Bleiedermatitt',
    'Pityriasis rosea',
    'Psoriasis',
    'Svettekjertelsykdom',
    'Talgcyste',
    'Inngrodd negl',
    'Molluscum contagiosum',
    'Akne',
    'Kronisk hudsår',
    'Urticaria',
    'Hud/underhud sykdom IKA',
    'Økt tørste',
    'Økt matlyst',
    'Nedsatt matlyst',
    'Ernæringsproblem hos spedbarn/barn',
    'Ernæringsproblem hos voksen',
    'Vektøkning',
    'Vekttap',
    'Forsinket vekst',
    'Uttørring',
    'Engstelig for kreft i det endokrine systemet',
    'Engstelig for sykd endokr/metabolske syst/ernæringssykd IKA',
    'Redusert funksjonsevne pga endokr/metabolsk/ernæringsproblem',
    'Endokrin/metabolsk/ernæring symptomer/plager IKA',
    'Infeksjon i det endokrine systemet',
    'Ondartet svulst i tyreoidea',
    'Godartet svulst i tyreoidea',
    'Svulst i endokrine organ IKA',
    'Ductus/cystis tyreoglossus',
    'Medfødt feil i endokrine/metabolske system IKA',
    'Struma',
    'Fedme',
    'Overvekt',
    'Hypertyreose/tyreotoksikose',
    'Hypotyreose/myksødem',
    'Hypoglykemi',
    'Diabetes type 1',
    'Diabetes type 2',
    'Vitaminmangel/ernæringsforstyrrelse',
    'Urinsyregikt',
    'Lipidstoffskifte forstyrrelse',
    'Endokrin/metabolsk/ernæringssykdom IKA',
    'Smerte ved vannlating',
    'Hyppig vannlating',
    'Urininkontinens',
    'Vannlatingsproblemer IKA',
    'Hematuri',
    'Urin symptomer/plager IKA',
    'Urinretensjon',
    'Blære symptomer/plager IKA',
    'Nyre symptomer/plager',
    'Engstelig for kreft i urinveiene',
    'Engstelig for sykdom i urinveiene IKA',
    'Redusert funksjonsevne pga urinveisproblem',
    'Urinveier symptomer/plager IKA',
    'Nyrebekkenbetennelse',
    'Cystitt/urinveisinfeksjon IKA',
    'Uretritt',
    'Ondartet svulst i nyre',
    'Ondartet svulst i urinblære',
    'Ondartet svulst i urinveiene IKA',
    'Godartet svulst i urinveiene',
    'Uspesifisert svulst i urinveiene',
    'Skade i urinveiene',
    'Medfødt feil i urinveiene',
    'Glomerulonefritt/nefropati',
    'Ortostatisk proteinuri',
    'Sten i urinveiene',
    'Unormal urinprøve IKA',
    'Urinveissykdom IKA',
    'Spørsmål om svangerskap',
    'Engstelig for svangerskap',
    'Blødning i svangerskap',
    'Kvalme/brekninger i svangerskap',
    'Prevensjon postkoital antikonsepsjon',
    'Prevensjon p-pille',
    'Prevensjon spiral',
    'Sterilisering kvinne',
    'Prevensjon IKA kvinne',
    'Infertilitet kvinne',
    'Blødning etter fødsel',
    'Postpartum symptomer/plager IKA',
    'Amming symptomer/plager',
    'Bekymret/opptatt av utseende i svangerskap',
    'Engstelig for komplikasjoner ved svangerskap/fødsel',
    'Redusert funksjonsevne pga svangerskapsproblem',
    'Svangerskap/fødsel symptomer/plager IKA',
    'Infeksjon/sepsis i barseltid',
    'Infeksjon som kompliserer svangerskap IKA',
    'Ondartet svulst knyttet til svangerskap',
    'Godartet/uspesifisert svulst knyttet til svangerskap',
    'Skade som kompliserer svangerskap',
    'Medfødt feil som kompliserer svangerskap',
    'Svangerskap bekreftet',
    'Svangerskapskontroll',
    'Uønsket svangerskap',
    'Ekstrauterint svangerskap',
    'Svangerskapsforgiftning',
    'Abort spontan',
    'Abort fremkalt',
    'Svangerskap høyrisiko',
    'Svangerskapsdiabetes',
    'Ukomplisert fødsel levendefødt barn',
    'Ukomplisert fødsel dødfødt barn',
    'Komplisert fødsel levendefødt barn',
    'Komplisert fødsel dødfødt barn',
    'Mastitt i barseltid',
    'Brystsykdom i svangerskap/barseltid IKA',
    'Komplikasjoner i barseltid IKA',
    'Svangerskap/fødsel/barseltid sykdom IKA',
    'Smerte i kjønnsorgan kvinne',
    'Menstruasjonssmerter',
    'Intermenstruelle smerter',
    'Smerte ved samleie kvinne',
    'Menstruasjon sparsom/sjelden',
    'Menstruasjon kraftig',
    'Menstruasjon uregelmessig/hyppig',
    'Intermenstruell blødning',
    'Premenstruelle symptomer/plager',
    'Forskyvning av menstruasjon',
    'Klimakterium symptomer/plager',
    'Postmenopausal blødning',
    'Blødning etter samleie',
    'Utflod fra skjeden',
    'Skjede symptomer/plager IKA',
    'Vulva symptomer/plager',
    'Underliv symptomer/plager kvinne',
    'Smerte i bryst kvinne',
    'Kul i bryst IKA kvinne',
    'Brystvorte symptomer/plager kvinne',
    'Bryst symptomer/plager IKA kvinne',
    'Bekymret/opptatt av brystenes utseende kvinne',
    'Engstelig for kjønnssykdom kvinne',
    'Engstelig for seksuell dysfunksjon kvinne',
    'Engstelig for kreft i kjønnsorgan kvinne',
    'Engstelig for brystkreft kvinne',
    'Engstelig for sykdom i kjønnsorgan/bryst IKA kvinne',
    'Redusert funksjonsevne pga problem i kjønnsorgan kvinne',
    'Kjønnsorgan symptomer/plager IKA kvinne',
    'Syfilis kvinne',
    'Gonokokkinfeksjon kvinne',
    'Candidainfeksjon urogenitalt kvinne',
    'Trikomonasinfeksjon urogenitalt kvinne',
    'Underlivsinfeksjon IKA kvinne',
    'Ondartet svulst i livmorhals',
    'Ondartet svulst i bryst kvinne',
    'Ondartet svulst i kvinnelige kjønnsorgan IKA',
    'Godartet svulst i livmor',
    'Godartet svulst i bryst kvinne',
    'Godartet svulst i kvinnelige kjønnsorgan IKA',
    'Uspesifisert svulst i kvinnelige kjønnsorgan IKA',
    'Skade i kvinnelige kjønnsorgan',
    'Medfødt feil i kvinnelige kjønnsorgan',
    'Vaginitt/vulvitt IKA',
    'Sykdom i livmorhals IKA',
    'Cytologi livmorhals unormal',
    'Fremfall av kvinnelige kjønnsorgan',
    'Godartet mammadysplasi',
    'Premenstruelt tensjonssyndrom',
    'Genital herpesvirusinfeksjon kvinne',
    'Condylomata acuminata kvinne',
    'Klamydiainfeksjon urogenitalt kvinne',
    'Sykdom i kvinnelige kjønnsorgan IKA',
    'Smerte i penis',
    'Smerte i testikkel/skrotum',
    'Utflod fra urinrør/penis',
    'Penis symptomer/plager IKA',
    'Skrotum/testikkel symptomer/plager IKA',
    'Prostata symptomer/plager',
    'Impotens organisk betinget',
    'Seksuelt problem IKA mann',
    'Infertilitet mann',
    'Sterilisering mann',
    'Prevensjon IKA mann',
    'Bryst symptomer/plager mann',
    'Engstelig for seksuell dysfunksjon mann',
    'Engstelig for kjønnssykdom mann',
    'Engstelig for kreft i kjønnsorgan mann',
    'Engstelig for sykdom i kjønnsorgan IKA mann',
    'Redusert funksjonsevne pga problem i kjønnsorgan mann',
    'Kjønnsorgan symptomer/plager IKA mann',
    'Syfilis mann',
    'Gonokokkinfeksjon mann',
    'Genital herpesvirusinfeksjon mann',
    'Prostatitt/vesikulitt',
    'Orkitt/epididymitt',
    'Balanopostitt',
    'Condylomata acuminata mann',
    'Ondartet svulst i prostata',
    'Ondartet svulst i mannlige kjønnsorgan IKA',
    'Godartet/uspesifisert svulst i mannlige kjønnsorgan',
    'Skade i mannlige kjønnsorgan',
    'Fimose/overflødig forhud',
    'Hypospadi',
    'Ikke-descendert testikkel',
    'Medfødt feil i mannlige kjønnsorgan IKA',
    'Prostatahyperplasi',
    'Hydrocele',
    'Sykdom i mannlige kjønnsorgan IKA',
    'Problem med økonomi/fattigdom',
    'Problem med drikkevann/mat',
    'Problem med bolig/nabolag',
    'Problem sosialt/kulturelt',
    'Problem med arbeidsforhold/yrke',
    'Problem med arbeidsledighet',
    'Problem med utdannelse',
    'Problem med sosial velferd/trygd',
    'Problem med jus/politi',
    'Problem med helsetjenester/tilgjengelighet',
    'Problem med det å være syk/compliance',
    'Problemer mellom samlivspartnere',
    'Problem med atferd til samlivspartner',
    'Problem med sykdom hos samlivspartner',
    'Problem ved tap/dødsfall av samlivspartner',
    'Problem med/i forhold til barn',
    'Problem med sykdom hos barn',
    'Problem ved tap/dødsfall av barn',
    'Problem med forhold til foreldre/familiemedlem',
    'Problem med atferd til forelde/familiemedlem',
    'Problem med sykdom hos foreldre/familiemedlem',
    'Problem ved tap/dødsfall av foreldre/familiemedlem',
    'Problem med forhold til venner',
    'Problem som følge av vold/traumatisk hendelse',
    'Engstelig for sosialt problem',
    'Redusert funksjonsevne pga sosialt problem',
    'Sosialt problem IKA',
];
