export declare const answerOptionContent: string;
export declare const answerOptionInputs: string;
export declare const answerOptionItem: string;
export declare const answerOptionLabel: string;
export declare const extensions: string;
export declare const extensionsContainer: string;
export declare const includeHeader: string;
export declare const valueSetCompose: string;
export declare const valueSetComposeDetails: string;
