pid /tmp/nginx.pid;
error_log /dev/stderr;

events {}

http {
    access_log /dev/stdout;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile    on;
    gzip_static on;

    server {
        listen 8080;
        listen [::]:8080;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
